-- Du lieu mau danh muc benh truyen nhiem
-- Nguon: Danh muc 01 - Phu luc I, Quyet dinh 97/QD-PB ngay 30/6/2026 (Cuc Phong benh)
-- Ma ICD-10 theo Thong tu 06/2026/TT-BYT. ky_han_bao_cao: 24h | 48h | tuan
-- Luu y: nhom_phan_loai A/B/C xac dinh rieng theo diem so Dieu 14-15 & Phu luc I TT15,
--        KHONG suy tu ky han bao cao; cot ky_han_bao_cao duoi day lay truc tiep tu Danh muc 01 QD97.

INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN001', 'Bệnh bại liệt', '24h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN002', 'Bệnh dịch hạch', '24h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN003', 'Bệnh do vi rút cúm A(H5N1)', '24h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN004', 'Bệnh do vi rút cúm A(H5N6)', '24h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN005', 'Bệnh do vi rút cúm A(H7N9)', '24h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN006', 'Bệnh do vi rút cúm A(H9N2)', '24h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN007', 'Bệnh do vi rút Ebola (Bệnh sốt xuất huyết do vi rút Ebola)', '24h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN008', 'Bệnh do vi rút Lassa (Bệnh sốt xuất huyết do vi rút Lassa)', '24h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN009', 'Bệnh do vi rút Marburg (Bệnh sốt xuất huyết do vi rút Marburg)', '24h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN010', 'Bệnh do vi rút Nipah', '24h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN011', 'Bệnh nhiễm vi rút tây sông Nin', '24h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN012', 'Bệnh sốt vàng', '24h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN013', 'Hội chứng suy hô hấp cấp tính nặng (SARS)', '24h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN014', 'Hội chứng viêm đường hô hấp vùng Trung Đông (MERS-CoV)', '24h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN015', 'Bệnh truyền nhiễm đặc biệt nguy hiểm mới phát sinh, chưa rõ tác nhân gây bệnh', '24h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN016', 'Bệnh bạch hầu', '24h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN017', 'Bệnh nhiễm trùng do não mô cầu', '24h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN018', 'Bệnh sởi', '24h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN019', 'Bệnh COVID-19', '48h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN020', 'Bệnh dại', '48h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN021', 'Bệnh đậu mùa khỉ (Mpox)', '48h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN022', 'Bệnh do nhiễm vi rút Chikungunya', '48h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN023', 'Bệnh do vi rút Hanta', '48h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN024', 'Bệnh nhiễm vi rút Zika', '48h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN025', 'Bệnh ho gà', '48h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN026', 'Bệnh liên cầu lợn ở người', '48h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN027', 'Bệnh rubella', '48h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN028', 'Bệnh sốt xuất huyết Dengue', '48h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN029', 'Bệnh sốt rét', '48h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN030', 'Bệnh tả', '48h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN031', 'Bệnh tay - chân - miệng', '48h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN032', 'Bệnh than', '48h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN033', 'Bệnh uốn ván', '48h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN034', 'Bệnh viêm gan vi rút A', '48h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN035', 'Bệnh viêm não Nhật Bản', '48h');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN036', 'Bệnh cúm', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN037', 'Bệnh do Haemophilus influenzae', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN038', 'Bệnh do nhiễm Listeria', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN039', 'Bệnh do nhiễm nocardia', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN040', 'Bệnh do phế cầu', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN041', 'Bệnh do vi rút Adeno khác', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN042', 'Bệnh viêm kết mạc do vi rút Adeno', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN043', 'Bệnh do vi rút gây ra hội chứng suy giảm miễn dịch mắc phải ở người (HIV/AIDS)', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN044', 'Bệnh do vi rút hợp bào hô hấp (RSV)', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN045', 'Bệnh do vi rút HPV (Human Papilloma Virus) ở người', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN046', 'Bệnh lao', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN047', 'Bệnh Legionnaire', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN048', 'Bệnh leptospira', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN049', 'Bệnh quai bị', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN050', 'Bệnh thương hàn', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN051', 'Bệnh thủy đậu', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN052', 'Bệnh tiêu chảy do vi rút Rota', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN053', 'Bệnh viêm gan vi rút B', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN054', 'Bệnh viêm gan vi rút C', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN055', 'Bệnh viêm gan vi rút D', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN056', 'Bệnh viêm gan vi rút E', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN057', 'Bệnh viêm não vi rút', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN058', 'Bệnh viêm phế quản cấp tính do vi rút Coxsackie', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN059', 'Bệnh melioidosis (Whitmore)', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN060', 'Ngộ độc botulinum', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN061', 'Bệnh nhiễm ấu trùng sán lợn', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN062', 'Bệnh đường ruột do nhiễm giardia', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN063', 'Bệnh nhiễm giun', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN064', 'Bệnh giun đũa chó mèo', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN065', 'Bệnh do nhiễm nấm Candida', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN066', 'Bệnh do nhiễm Rickettsia', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN067', 'Bệnh nhiễm sán dây', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN068', 'Bệnh nhiễm sán dây chó', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN069', 'Bệnh nhiễm sán lá gan', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN070', 'Bệnh nhiễm sán lá phổi', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN071', 'Bệnh nhiễm sán lá ruột', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN072', 'Bệnh do trichomonas', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN073', 'Bệnh nhiễm vi rút đại bào', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN074', 'Bệnh do nhiễm vi rút herpes', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN075', 'Bệnh giang mai', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN076', 'Bệnh lậu', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN077', 'Bệnh lỵ a-míp', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN078', 'Bệnh lỵ trực khuẩn', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN079', 'Bệnh mắt hột', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN080', 'Bệnh phong', 'tuan');
INSERT INTO dm_benh_truyen_nhiem (ma_benh, ten_benh, ky_han_bao_cao) VALUES ('BTN081', 'Ngộ độc thực phẩm do Vibrio Parahaemolyticus', 'tuan');

-- Ma ICD-10 chi tiet (1 benh co the co nhieu ma)
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A80' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN001';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A20' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN002';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'J09' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN003';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'J09' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN004';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'J09' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN005';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'J09' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN006';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A98.4' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN007';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A96.2' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN008';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A98.3' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN009';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B33.8' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN010';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A92.3' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN011';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A95' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN012';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'U04' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN013';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B34.2' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN014';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A36' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN016';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A39' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN017';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B05' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN018';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'U07.1' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN019';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'U07.2' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN019';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A82' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN020';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B04' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN021';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A92.0' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN022';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A98.5' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN023';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B33.4' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN023';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A92.5' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN024';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'P35.4' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN024';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A37' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN025';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A40.8' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN026';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'G00.2' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN026';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B06' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN027';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'P35.0' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN027';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A97' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN028';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B50 - B54' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN029';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A00' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN030';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B08.4' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN031';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A22' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN032';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A33 - A35' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN033';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B15' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN034';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A83.0' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN035';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'J10' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN036';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'J11' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN036';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'G00.0' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN037';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A41.3' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN037';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'J14' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN037';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'J05.1' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN037';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'J20.1' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN037';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A32' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN038';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'P37.2' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN038';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A43' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN039';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'J13' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN040';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A40.3' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN040';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'G00.1' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN040';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'M00.1' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN040';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A87.1' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN041';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A85.1' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN041';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A08.2' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN041';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B34.0' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN041';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'J12.0' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN041';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B30.0' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN042';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B30.1' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN042';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B20-B24' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN043';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'Z20.6' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN043';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'Z21' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN043';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'J12.1' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN044';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'J20.5' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN044';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'J21.0' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN044';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B07' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN045';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A63.0' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN045';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A15' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN046';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A16' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN046';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A48.1' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN047';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A48.2' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN047';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A27' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN048';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B26' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN049';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A01' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN050';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B01' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN051';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A08.0' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN052';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B16' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN053';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B18.0' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN053';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B18.1' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN053';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B17.1' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN054';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B18.2' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN054';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B17.0' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN055';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B17.2' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN056';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A83 - A86' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN057';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'G04.8' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN057';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'G04.9' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN057';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'J20.3' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN058';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A24' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN059';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A05.1' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN060';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B69' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN061';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A07.1' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN062';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B72 - B75' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN063';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B76 - B81' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN063';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B83' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN063';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B83.0' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN064';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B37' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN065';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B20.4' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN065';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A75.0' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN066';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A75.2' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN066';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A77' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN066';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A79' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN066';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B68' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN067';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B70' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN067';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B71' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN067';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B67' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN068';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B66' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN069';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B66.4' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN070';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B66.5' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN071';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B66.8' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN071';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A59' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN072';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B20.2' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN073';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B25' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN073';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B27.1' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN073';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'P35.1' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN073';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A60' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN074';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B00' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN074';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'B02' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN074';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'P35.2' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN074';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A50 - A53' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN075';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A65' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN075';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A54' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN076';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A06' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN077';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A03' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN078';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A71' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN079';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A30' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN080';
INSERT INTO dm_benh_truyen_nhiem_icd10 (benh_id, ma_icd10) SELECT id, 'A05.3' FROM dm_benh_truyen_nhiem WHERE ma_benh = 'BTN081';
